In [1]:
#step1
import pandas as pd
df=pd.read_csv("windpower.csv")
df.head()

   Power (kW)  Wind speed (m/s)
0         0.0             0.000
1         0.0             0.125
2         0.0             0.150
3         0.0             0.225
4         0.0             0.275

In [2]:
#step2 
df.isna().sum()

Power (kW)          3
Wind speed (m/s)    5
dtype: int64

In [5]:
#step3
df.dropna(inplace=True)
df.head()

   Power (kW)  Wind speed (m/s)
0         0.0             0.000
1         0.0             0.125
2         0.0             0.150
3         0.0             0.225
4         0.0             0.275

In [8]:
y=df["Power (kW)"]
x=df[["Wind speed (m/s)"]]
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(369, 1)
(123, 1)
(369,)
(123,)

In [18]:
from sklearn.preprocessing import PolynomialFeatures
deg=[3,4,5,6]
for i in deg:
        poly=PolynomialFeatures(degree=i)
poly
x_train.head()

     Wind speed (m/s)
115             5.956
359            18.043
139             7.082
196            10.085
322            16.441

In [19]:
x_train_poly=poly.fit_transform(x_train)
x_train_poly

array([[1.00000000e+00, 5.95600000e+00, 3.54739360e+01, ...,
        1.25840014e+03, 7.49503121e+03, 4.46404059e+04],
       [1.00000000e+00, 1.80430000e+01, 3.25549849e+02, ...,
        1.05982704e+05, 1.91224593e+06, 3.45026533e+07],
       [1.00000000e+00, 7.08200000e+00, 5.01547240e+01, ...,
        2.51549634e+03, 1.78147451e+04, 1.26164025e+05],
       ...,
       [1.00000000e+00, 1.77930000e+01, 3.16590849e+02, ...,
        1.00229766e+05, 1.78338822e+06, 3.17318266e+07],
       [1.00000000e+00, 2.22970000e+01, 4.97156209e+02, ...,
        2.47164296e+05, 5.51102231e+06, 1.22879264e+08],
       [1.00000000e+00, 5.50600000e+00, 3.03160360e+01, ...,
        9.19062039e+02, 5.06035559e+03, 2.78623179e+04]], shape=(369, 7))