classification Algorithm --->KNN
                            --->Decision Tree

knn-->k-nearest Neighbors

distance=  root(x2-x1)^2+(y2-y1)^2
-->specific category maa data devide kare(like yes or no) 
-->k ni value odd complsory levani karne ke accurate answer prdict kari sakaie 
-->k ti nearest data hoy tane based upar ti prdicat kari sakie

-->offline exam 6 marks code (MIMP)
MI vs RCB
TP-3
TN-2
FP-2
FN-2

predicted  actual
win         win  --->T(ane actual pan win thaie tathi true aavse)--actual / P(win etla postive)--predicted
win         loss --->F(aapdu prediction khotu che etla false based on actual data)P(prdict win che etla postive aavse)
loss        win  FN
loss        loss  TN
win         loss  FP
loss        win   FN
win         win    TP
loss        loss   TN
win         win   TP

confussion metrix=[[TN,FP],
                   [FN,TP]]
TN=cm[0][0]
FP=cm[0][1]
FN=cm[1][0]
TP=cm[1][1]
        Predicted
     |  no  | yes 
___________ |______
 no  |TN   |FP
 yes |FN   |TP

actual   Predicted
     |  no  | yes 
_____|______|______
 no  |TN    |FP
 yes |FN    |TP

[1] Accuracy= (TP+TN)/(TP+TN+FP+FN)
[2] Error=(FP+FN)/(TP+TN+FP+FN)
[3]Sensitivity(positvie direction)= TP/TP+FN(based on table show the value of yes)--->actual value maa YES jovanu table maa
[4]Speciticity(negatvie direction)=TN/TN+FP(based on table show the value of no)---->actual value maa NO jovanu table maa

In [3]:
#step 1
import pandas as pd
import numpy as np
df=pd.read_csv("diabetes.csv")
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [4]:
#null value
df.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [9]:
y=df["Outcome"]
x=df[['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age']]

In [7]:
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
print(x_train.shape)#614 rows nu squreroot karvanu 614**0.5 ans 24.77 aave etla k ni value aapde 25 laiesu ane k ni value odd jaa hovie joie
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(614, 8)
(154, 8)
(614,)
(154,)

In [19]:
from sklearn.neighbors import KNeighborsClassifier
nn= KNeighborsClassifier(n_neighbors=25)

In [21]:
model=nn.fit(x_train,y_train)
model

KNeighborsClassifier(n_neighbors=25)

In [22]:
#dibetes che ke nai
y_pred=model.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0])

In [26]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)#table par ti aa value madie
cm

array([[83, 16],
       [28, 27]])

In [32]:
TN=cm[0][0]
FP=cm[0][1]
FN=cm[1][0]
TP=cm[1][1]
print("TN=",TN)
print("FP=",FP)
print("FN=",FN)
print("TP=",TP)

TN= 83
FP= 16
FN= 28
TP= 27

In [43]:
Accuracy=(TP+TN)/(TP+TN+FP+FN)
print("Accuracy",Accuracy)
Error=(FP+FN)/(TP+TN+FP+FN)
print("Error:",Error)
Sensitivity=TP/(TP+FN)#TP nu opposite FN
print("Sensitivity",Sensitivity)
Speciticity=TN/(TN+FP)
print("Speciticity:",Speciticity)

Accuracy 0.7142857142857143
Error: 0.2857142857142857
Sensitivity 0.4909090909090909
Speciticity: 0.8383838383838383

In [44]:
#preg:4,glu:85,bP:55,ST:30,IN:180,BMI:29.0,DP:0.5,age:51
die=model.predict([[4,85,55,30,180,29.0,0.5,51]])
die

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

array([0])

In [113]:
#playtennise 
#-->tennise ramva jaie sakies nai based on whether
import pandas as pd
df=pd.read_csv("PlayTennis.csv")
df.head()

    outlook  temp humidity  windy play
0     sunny   hot     high  False   no
1     sunny   hot     high   True   no
2  overcast   hot     high  False  yes
3     rainy  mild     high  False  yes
4     rainy  cool   normal  False  yes

In [114]:
df=pd.get_dummies(data=df,drop_first=True)#drop_first actual columns delete kari de 
df

,windy,outlook_rainy,outlook_sunny,temp_hot,temp_mild,humidity_normal,play_yes
0,False,False,True,True,False,False,False
1,True,False,True,True,False,False,False
2,False,False,False,True,False,False,True
3,False,True,False,False,True,False,True
4,False,True,False,False,False,True,True
5,True,True,False,False,False,True,False
6,True,False,False,False,False,True,True
7,False,False,True,False,True,False,False
8,False,False,True,False,False,True,True
9,False,True,False,False,True,True,True
10,True,False,True,False,True,True,True
11,True,False,False,False,True,False,True
12,False,False,False,True,False,True,True
13,True,True,False,False,True,False,False

In [115]:
y=df["play_yes"]
x=df[['windy', 'outlook_rainy', 'outlook_sunny', 'temp_hot', 'temp_mild',
       'humidity_normal']]

In [116]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(11, 6)
(3, 6)
(11,)
(3,)

In [117]:
from sklearn.neighbors import KNeighborsClassifier
nn= KNeighborsClassifier(n_neighbors=3)

In [118]:
model=nn.fit(x_train,y_train)
y_pred=model.predict(x_test)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[0, 1],
       [1, 1]])

In [119]:
TN=cm[0][0]
FP=cm[0][1]
FN=cm[1][0]
TP=cm[1][1]
print("TN=",TN)
print("FP=",FP)
print("FN=",FN)
print("TP=",TP)

TN= 0
FP= 1
FN= 1
TP= 1

In [120]:
Accuracy=(TP+TN)/(TP+TN+FP+FN)
print("Accuracy",Accuracy)
Error=(FP+FN)/(TP+TN+FP+FN)
print("Error:",Error)
Sensitivity=TP/(TP+FN)#TP nu opposite FN
print("Sensitivity",Sensitivity)
Speciticity=TN/(TN+FP)
print("Speciticity:",Speciticity)

Accuracy 0.3333333333333333
Error: 0.6666666666666666
Sensitivity 0.5
Speciticity: 0.0

In [121]:
df.columns

Index(['windy', 'outlook_rainy', 'outlook_sunny', 'temp_hot', 'temp_mild',
       'humidity_normal', 'play_yes'],
      dtype='object')

In [123]:
#rainly,cool,high,windy
pred=model.predict([[1,1,0,0,0,0]])
pred

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

array([False])

In [136]:
#--->cancer
import pandas as pd
df=pd.read_csv("data_breast_cancer.csv")
df

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,NaN
565,926682,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,NaN
566,926954,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,NaN
567,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,NaN
568,92751,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,...,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039,NaN

In [137]:
df.isna().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed: 32                569
dtype: int64

In [138]:
df.drop(columns="Unnamed: 32",inplace=True)
df.drop(columns="id",inplace=True)
df

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [139]:
df.columns

Index(['diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst'],
      dtype='object')

In [143]:
x=df[['radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst']]
y=df['diagnosis']

In [145]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)
455**0.5

(455, 30)
(114, 30)
(455,)
(114,)

21.330729007701542

In [146]:
from sklearn.neighbors import KNeighborsClassifier
nn= KNeighborsClassifier(n_neighbors=21)

In [147]:
model=nn.fit(x_train,y_train)
y_pred=model.predict(x_test)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[71,  0],
       [ 4, 39]])

In [148]:
TN=cm[0][0]
FP=cm[0][1]
FN=cm[1][0]
TP=cm[1][1]
print("TN=",TN)
print("FP=",FP)
print("FN=",FN)
print("TP=",TP)

TN= 71
FP= 0
FN= 4
TP= 39

In [149]:
Accuracy=(TP+TN)/(TP+TN+FP+FN)
print("Accuracy",Accuracy)
Error=(FP+FN)/(TP+TN+FP+FN)
print("Error:",Error)
Sensitivity=TP/(TP+FN)#TP nu opposite FN
print("Sensitivity",Sensitivity)
Speciticity=TN/(TN+FP)
print("Speciticity:",Speciticity)

Accuracy 0.9649122807017544
Error: 0.03508771929824561
Sensitivity 0.9069767441860465
Speciticity: 1.0

In [ ]:
pred=model.predict([[1,1,0,0,0,0]])
pred